library chat1.globals;
import "package:chat1/models/chatUsersModel.dart";
bool isLoggedIn = false;
bool french=false;
String? token=null;
int? sessionId;
String apiUrl="http://0c1f-41-108-78-209.ngrok-free.app";
String socketurl="https://afraid-lamps-cut.loca.lt/";
Profile userprofile=new Profile(username: "", first_name: "", last_name: "", last_login: "", email: "",avatar:"/static/default.jpg");
bool humanhandoff=false;